### ISSUE TITLE
rpy2 rinterface Library not loaded: @rpath/libicuuc.54.dylib/image not found

### ISSUE THREAD

**Issue by SilasK** [cstoeckert/iterativeWGCNA#19]
Hallo,

I installed python 3.6 and r and rpy2 r-wgcna via conda and iterativeWGCNA via pip on my mac.

when I run `iterativeWGCNA` I get the following error.
the same happens when I download and install the version from git. 

```
Traceback (most recent call last):
  File "/Users/silas/anaconda3/envs/wgcna/bin/iterativeWGCNA", line 9, in <module>
    from iterativeWGCNA.iterativeWGCNA import IterativeWGCNA
  File "/Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/iterativeWGCNA/iterativeWGCNA.py", line 16, in <module>
    import rpy2.robjects as ro
  File "/Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicuuc.54.dylib
  Referenced from: /Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by fossilfriend** [comment]
Hi-

This appears to be an anaconda issue:

```
ImportError: dlopen(/Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicuuc.54.dylib

 Referenced from: /Users/silas/anaconda3/envs/wgcna/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so
  Reason: image not found
```

and may potentially be resolved by updating the anaconda packages:

https://bitbucket.org/rpy2/rpy2/issues/402/error-importing-rpy2robject-library-not

or uninstalling conda-forge and installing the r-base manually:

https://github.com/conda-forge/conda-forge.github.io/issues/234

Unfortunately we do not use anaconda so I can't be much more help in debugging this issue.
